name: Update V2Ray Subscription

on:
  schedule:
    - cron: '*/5 * * * *'  # هر 5 دقیقه
  workflow_dispatch:

jobs:
  update-subscription:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch raw configs and build mahsa-free-config.txt
        run: python mahsa-free-config.py   # 🔹 این فایل همونیه که mahsa-free-config.txt می‌سازه

      - name: Run subscription updater
        run: python make_sub.py
        env:
          GOTHUB_TOKEN: ${{ secrets.GOTHUB_TOKEN }}
